### ISSUE TITLE
Generate javadocs with xmvn-javadoc

### ISSUE THREAD

**Issue by deamn** [fedora-java/xmvn#110]
I try to build openjfx8 that need openjdk 1.8 with this command
`%mvn_build -f --xmvn-javadoc`

I added to the openjfx8.spec file these instructions:
```
BuildRequires:  maven-local-openjdk8
BuildRequires:  jakarta-annotations
```
The build failed on the javadoc generation step:
```
...
/builddir/build/BUILD/rt-8u202-b07/modules/builders/src/main/java/javafx/scene/control/ListViewBuilder.java:34: error: package javax.annotation does not exist
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
...
```
It seems that I need to add something like this but where?
`--add-modules=javax.annotation`

**Comment by mizdebsk** [comment]
Please provide a minimal reproducer so that I can investigate the issue.

**Comment by deamn** [comment]
Please try with git clone git://fedorapeople.org/home/fedora/deamn/public_git/openjfx8-fork.git
then fedpkg mockbuild

**Comment by mizdebsk** [comment]
Sorry, but I don't have time to debug the build for you. If you can isolate the issue as a minimal project (that can be used as integration test) then I can look into fixing it.

**Comment by deamn** [comment]
What do you mean with minimal project? A java 8 project with javadoc generation?
Do you execute xmvn with jdk module javax.annotation? (`--add-modules=javax.annotation`)
I will remove the openjfx8-javadoc from the build in meantime

**Comment by mizdebsk** [comment]
I mean a simple Maven project that demonstrates the issue.
Javadocs should generate with Maven Javadoc Plugin, but fail with XMvn Javadoc MOJO.
This will allow me to investigate the issue and fix it.
Without reproducer project I don't have enough information to fix the issue.

**Comment by deamn** [comment]
I understand the problem: the annotation @Generated was javax.annotation.Generated until java 8 but since java 9 is javax.annotation.processing.Generated. When xmvn build with compiler level 8, the build succeed but the XMvn Javadoc failed because it's running with java 11 (that need javax.annotation.processing.Generated). But if I change the annotation to javax.annotation.processing.Generated and I try to build with compiler level 8 it failed...
Ideally xmvn should treat this use case... but I don't know how... I will remove these annotations from source code, I think it will not break something in openjfx8. If the openjfx8 build will succeed, I will close this issue.

**Comment by mizdebsk** [comment]
Reopening, this looks like a valid issue. I will try to fix it in the future. A reproducer would help, but I can try to create one by myself.

**Comment by fridrich** [comment]
The first two commits in https://github.com/fedora-java/xmvn/pull/193 address this kind of issues
