### ISSUE TITLE
Allow filtering source files by regular expression

### ISSUE THREAD

**Issue by mizdebsk** [fedora-java/xmvn#161]
Implement equivalent of `excludePackageNames` option of Maven Javadoc Plugin.
This is required to build javadocs for [mariadb-connector-j](https://github.com/mariadb-corporation/mariadb-connector-j).

**Comment by mkoncek** [comment]
Started with integration tests: https://github.com/mkoncek/xmvn/commit/bd244721008909ba402cbe576fb9985afd08c5f8

**Comment by mizdebsk** [comment]
@mkoncek Is this feature still relevant?

**Comment by mkoncek** [comment]
Current `mariadb-java-client` in Fedora also builds javadocs. I checked them and they look reasonable.
So this feature is currently not needed.

**Comment by mizdebsk** [comment]
Due to the above I'm closing this issue for now.
Feel free to reopen it if the feature becomes relevant again.
