### ISSUE TITLE
Update to Java 17 for XMvn 5

### ISSUE THREAD

**Issue by mizdebsk** [fedora-java/xmvn#312]
I would like to update minimal Java version required to build and run XMvn to at least 17.
This change should happen in XMvn major version 5, but it's still a long way before I'll be able to make XMvn 5 release.

Update of Java to 17 will make it possible to start preparations for Maven 4 support, which requires Java 17+, https://maven.apache.org/docs/history.html

More context:
- Fedora 42 will drop all Java versions < 21
- RHEL 10 will ship with Java 21 only
- Red Hat OpenJDK support dates: https://access.redhat.com/articles/1299013

@fridrich As follow-up to #196 I would like to make sure that you are fine with this change now, as time passed and we are in a bit different situation now.

**Comment by fridrich** [comment]
I am fine to have that done for maven 4. At least one release of xmvn 4.x would not be really bad though.

**Comment by mizdebsk** [comment]
I'm planning to do a 4.3.0 release "soon" and I don't mind maintaining 4.x branch in parallel with 5.x
