### ISSUE TITLE
It should be easier to import project into Eclipse

### ISSUE THREAD

**Issue by Yky** [fedora-java/xmvn#36]
Several poms, such as xmvn-api have the following error: 

Plugin execution not covered by lifecycle configuration: org.apache.rat:apache-rat-plugin:0.12:check (execution: rat-check, phase: validate)

**Comment by Yky** [comment]
Thanks for fixing this. 

There are still problems with 5 poms in master with this error: 
xmvn-api:
```
Plugin execution not covered by lifecycle configuration: org.codehaus.modello:modello-maven-plugin:1.9.1:java (execution: standard, phase: generate-sources)	pom.xml	/xmvn-api	line 57	Maven Project Build Lifecycle Mapping Problem

Plugin execution not covered by lifecycle configuration: org.codehaus.modello:modello-maven-plugin:1.9.1:stax-reader (execution: standard, phase: generate-sources)	pom.xml	/xmvn-api	line 57	Maven Project Build Lifecycle Mapping Problem

Plugin execution not covered by lifecycle configuration: org.codehaus.modello:modello-maven-plugin:1.9.1:stax-writer (execution: standard, phase: generate-sources)	pom.xml	/xmvn-api	line 57	Maven Project Build Lifecycle Mapping Problem
```
xmvn-connector-aether:
`Plugin execution not covered by lifecycle configuration: org.codehaus.plexus:plexus-component-metadata:1.7.1:generate-metadata (execution: default, phase: process-classes)	pom.xml	/xmvn-connector-aether	line 22	Maven Project Build Lifecycle Mapping Problem`

xmvn-core:
`Plugin execution not covered by lifecycle configuration: org.codehaus.plexus:plexus-component-metadata:1.7.1:generate-metadata (execution: default, phase: process-classes)	pom.xml	/xmvn-core	line 22	Maven Project Build Lifecycle Mapping Problem`

xmvn-it:
```
Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-dependency-plugin:3.1.1:copy (execution: copy-artifacts, phase: process-test-resources)	pom.xml	/xmvn-it	line 120	Maven Project Build Lifecycle Mapping Problem
Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-dependency-plugin:3.1.1:unpack (execution: unpack-dist, phase: process-test-resources)	pom.xml	/xmvn-it	line 103	Maven Project Build Lifecycle Mapping Problem
```
xmvn-mojo:
```
Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-plugin-plugin:3.5.2:descriptor (execution: default-descriptor, phase: process-classes)	pom.xml	/xmvn-mojo	line 94	Maven Project Build Lifecycle Mapping Problem
Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-plugin-plugin:3.5.2:descriptor (execution: mojo-descriptor, phase: process-classes)	pom.xml	/xmvn-mojo	line 97	Maven Project Build Lifecycle Mapping Problem
```

**Comment by mizdebsk** [comment]
@Yky If you use packaged Eclipse then these problems can be solved by installing appropriate M2E connector packages: `eclipse-m2e-modello`, `eclipse-m2e-plexus`, `eclipse-m2e-maven-dependency-plugin`, `eclipse-m2e-mavendev`. If you use upstream Eclipse then these connectors can be installed from Eclipse Marketplace.
