### ISSUE TITLE
Javadoc Mojo cannot handle true "modular" projects

### ISSUE THREAD

**Issue by mbooth101** [fedora-java/xmvn#58]
For projects using the "module path" instead of the "class path" the javadoc mojo does not work. You see errors such as this:

```
[INFO] --- xmvn-mojo:3.1.0:javadoc (default-cli) @ jakarta.xml.bind-api ---
/home/mbooth/git/jaxb-api/jaxb-api/src/main/java/module-info.java:18: error: module not found: jakarta.activation
    requires transitive jakarta.activation;
                               ^
```

I was able to successfully build Javadoc with xmvn by making this change:

```
diff --git a/xmvn-mojo/src/main/java/org/fedoraproject/xmvn/mojo/JavadocMojo.java b/xmvn-mojo/src/main/java/org/fedoraproject/xmvn/mojo/JavadocMojo.java
index 173bdaa9..e140852d 100644
--- a/xmvn-mojo/src/main/java/org/fedoraproject/xmvn/mojo/JavadocMojo.java
+++ b/xmvn-mojo/src/main/java/org/fedoraproject/xmvn/mojo/JavadocMojo.java
@@ -215,7 +215,7 @@ public class JavadocMojo
             opts.add( "-version" );
             opts.add( "-Xdoclint:none" );
 
-            opts.add( "-classpath" );
+            opts.add( "--module-path" );
             opts.add( quoted( StringUtils.join( getClasspath().iterator(), ":" ) ) );
             opts.add( "-encoding" );
             opts.add( quoted( encoding ) );
```

But I would be surprised if it was as simple as passing `--module-path` instead of `-classpath` for modular projects. The maven-javadoc-plugin seems to have some amount of code for dealing with it: https://github.com/apache/maven-javadoc-plugin/blob/master/src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java

**Comment by mizdebsk** [comment]
In XMvn there is no support for JPMS yet, but I will try to add it, at least to Javadoc MOJO.
It would help if you could provide a simple project demonstrating the issue that could be used as a test case - ideally modularize `xmvn-it/src/test/resources/testJavadoc` test case and add it as a new test, eg. `testJavadocModules`.

**Comment by mbooth101** [comment]
> In XMvn there is no support for JPMS yet, but I will try to add it, at least to Javadoc MOJO.
> It would help if you could provide a simple project demonstrating the issue that could be used as a test case - ideally modularize `xmvn-it/src/test/resources/testJavadoc` test case and add it as a new test, eg. `testJavadocModules`.

Sure I can probably do that

**Comment by mbooth101** [comment]
I pushed this change to a branch on my fork: https://github.com/mbooth101/xmvn/commit/bbab8b4713c779305f762d3e62a354b606ed3f66

In which I added an IT, and you can compare the output like this:

```
$ cd xmvn-it/src/test/resources/testJavadocJPMS
$ JAVA_HOME=/usr/lib/jvm/java-11 mvn clean verify javadoc:aggregate
... successful build ...
$ JAVA_HOME=/usr/lib/jvm/java-11 mvn clean verify org.fedoraproject.xmvn:xmvn-mojo:4.0.0-SNAPSHOT:javadoc
... failed build ...
```

Does that help?
