### ISSUE TITLE
Using javadoc-mojo results in failed requires generation

### ISSUE THREAD

**Issue by msimacek** [fedora-java/xmvn#6]
`Exception: Unable to generate requires on unresolvable artifacts: org.apache.maven.plugins:maven-javadoc-plugin`

**Comment by mizdebsk** [comment]
I'll investigate that.

**Comment by mizdebsk** [comment]
Not reproducible for me, tested with:
- `xmvn-mojo-2.6.0-0.git.20160923.094808.noarch`
- `javapackages-tools-5.0.0-0.git.20160829.164625.noarch`

@msimacek Can you provide steps to reproduce this issue?

**Comment by msimacek** [comment]
It occurs in pom only subpackages that declare dep on maven-javadoc-plugin.
Reproducer: https://msimacek.fedorapeople.org/gossip-2.0.0-1.fc24.src.rpm (nonsensical edit of existing package)

**Comment by mizdebsk** [comment]
This behaviour is expected and not specific to javadoc plugin in any way. If have a binary package with only parent POM(s), all plugins listed in these POMs are generated as auto-requires, but requires generator needs to resolve them to know what namespace and version to use in generated requires, therefore all plugins must be installed. The same error will occur even if you remove javadoc plugin from POM and/or build without javadoc mojo (javodocs skipped).
