### ISSUE TITLE
Silence javadoc stdout

### ISSUE THREAD

**Issue by msimacek** [fedora-java/xmvn#7]
The output contains thousands of
`Generating /builddir/build/BUILD/jetty.project-jetty-9.4.0.RC0/target/apidocs/com/acme/fragment/FragmentServlet.html...`
lines, that are IMO useless and belong to `/dev/null`

**Comment by mizdebsk** [comment]
> lines, that are IMO useless and belong to /dev/null

Agreed, will be fixed.
