### ISSUE TITLE
Inspect CI build errors

### ISSUE THREAD

**Issue by mkoncek** [fedora-java/xmvn#76]
In a CI build on lines around 3514 there are a few build errors.

**Comment by mizdebsk** [comment]
Can you be more specific? What errors? Can you provide a link to the build?

**Comment by mkoncek** [comment]
For example here:
https://github.com/fedora-java/xmvn/runs/2960499301?check_suite_focus=true#step:4:3514

**Comment by mizdebsk** [comment]
These are in Gradle connector, which is being removed. They will go away once #68 is closed.
